[build]
builder = "nixpacks"
buildCommand = "cd socialpoint_backend && npm install"

[deploy]
startCommand = "cd socialpoint_backend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
workdir = "socialpoint_backend"

# Link database plugin
[plugins.postgres]
enabled = true 