export enum Category {
    CONCERT = "CONCERT",
    FESTIVAL = "FESTIVAL",
    CONFERENCE = "CONFERENCE",
    MEETING = "MEETING",
    SOCIAL = "SOCIAL",
    MUSIC = "MUSIC",
    EDUCATION = "EDUCATION",
    WORKSHOP = "WORKSHOP",
    OTHER = "OTHER"
}   